# Pandas DataFrame loc boolean mask

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:/Users/91701/Desktop/Dataset/worldcities2.csv", encoding='latin-1')

In [3]:
data

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
0,Saint-Oblas,Saint-Oblas,NaN,45.5674,5.0447,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,129.2,NaN,NaN,4,Europe/Paris,False,1250867231
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
3,Olmet,Olmet,NaN,44.9542,2.6108,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,71.0,NaN,NaN,4,Europe/Paris,True,1250526008
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59059,La Rochette,La Rochette,Rochette,45.2609,6.2881,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,55.5,NaN,NaN,4,Europe/Paris,True,1250239167
59060,La Rochette,La Rochette,NaN,45.3056,3.4747,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,14.4,NaN,NaN,4,Europe/Paris,True,1250909356
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59062,Saint-Eutrope,Saint-Eutrope,NaN,44.4535,0.5204,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,34.2,NaN,NaN,4,Europe/Paris,True,1250000461
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [4]:
data.columns

Index(['city', 'city_ascii', 'city_alt', 'lat', 'lng', 'country', 'iso2',
       'iso3', 'admin_name', 'admin_name_ascii', 'admin_code', 'admin_type',
       'capital', 'density', 'population', 'population_proper', 'ranking',
       'timezone', 'same_name', 'id'],
      dtype='object')

In [5]:
data.loc[0:5,['city']]

          city
0  Saint-Oblas
1     Louresse
2        Olmet
3        Olmet
4  Gottenhouse
5      Bergues

In [8]:
data.loc[0:5,['city','population']]

          city  population
0  Saint-Oblas         NaN
1     Louresse       872.0
2        Olmet       161.0
3        Olmet         NaN
4  Gottenhouse       382.0
5      Bergues      3637.0

# Another method

In [10]:
data.loc[0:5,'city':'country']

          city   city_ascii              city_alt      lat     lng country
0  Saint-Oblas  Saint-Oblas                   NaN  45.5674  5.0447  France
1     Louresse     Louresse  Louresse-Rochemenier  47.2394 -0.3136  France
2        Olmet        Olmet                   NaN  45.7100  3.6614  France
3        Olmet        Olmet                   NaN  44.9542  2.6108  France
4  Gottenhouse  Gottenhouse                   NaN  48.7208  7.3611  France
5      Bergues      Bergues                   NaN  50.9686  2.4342  France

# Boolean Mask

In [11]:
data

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
0,Saint-Oblas,Saint-Oblas,NaN,45.5674,5.0447,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,129.2,NaN,NaN,4,Europe/Paris,False,1250867231
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
3,Olmet,Olmet,NaN,44.9542,2.6108,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,71.0,NaN,NaN,4,Europe/Paris,True,1250526008
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59059,La Rochette,La Rochette,Rochette,45.2609,6.2881,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,55.5,NaN,NaN,4,Europe/Paris,True,1250239167
59060,La Rochette,La Rochette,NaN,45.3056,3.4747,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,14.4,NaN,NaN,4,Europe/Paris,True,1250909356
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59062,Saint-Eutrope,Saint-Eutrope,NaN,44.4535,0.5204,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,34.2,NaN,NaN,4,Europe/Paris,True,1250000461
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [12]:
data.country

0        France
1        France
2        France
3        France
4        France
          ...
59059    France
59060    France
59061    France
59062    France
59063    France
Name: country, Length: 59064, dtype: object

In [13]:
data['country']

0        France
1        France
2        France
3        France
4        France
          ...
59059    France
59060    France
59061    France
59062    France
59063    France
Name: country, Length: 59064, dtype: object

In [22]:
data['ranking']

0        4
1        3
2        3
3        4
4        3
        ..
59059    4
59060    4
59061    3
59062    4
59063    3
Name: ranking, Length: 59064, dtype: int64

In [23]:
data['ranking'].unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [24]:
len(data['ranking'].unique())

5

In [25]:
data['ranking'] == 3

0        False
1         True
2         True
3        False
4         True
         ...
59059    False
59060    False
59061     True
59062    False
59063     True
Name: ranking, Length: 59064, dtype: bool

In [26]:
data[data['ranking'] == 3] # when i need only ranking=3 values which is true

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
7,Saint-Martin-dâArrossa,Saint-Martin-d'Arrossa,Saint-Martin dâArrosa|Saint-Martin,43.2381,-1.3133,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,29.2,538.0,538.0,3,Europe/Paris,False,1250563131
8,Marre,Marre,NaN,49.2111,5.3019,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,16.0,163.0,163.0,3,Europe/Paris,False,1250424575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59056,Cognocoli-Monticchi,Cognocoli-Monticchi,Cognocoli-Montichi,41.8283,8.9058,France,FR,FRA,Corsica,Corsica,FR-H,region,NaN,4.8,171.0,171.0,3,Europe/Paris,False,1250310924
59057,La Rochette,La Rochette,NaN,45.4586,6.1203,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,804.1,3747.0,3747.0,3,Europe/Paris,False,1250715425
59058,La Rochette,La Rochette,NaN,44.9161,4.2408,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,4.3,60.0,60.0,3,Europe/Paris,True,1250888687
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [27]:
data.loc[data['ranking'] == 3]

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
7,Saint-Martin-dâArrossa,Saint-Martin-d'Arrossa,Saint-Martin dâArrosa|Saint-Martin,43.2381,-1.3133,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,29.2,538.0,538.0,3,Europe/Paris,False,1250563131
8,Marre,Marre,NaN,49.2111,5.3019,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,16.0,163.0,163.0,3,Europe/Paris,False,1250424575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59056,Cognocoli-Monticchi,Cognocoli-Monticchi,Cognocoli-Montichi,41.8283,8.9058,France,FR,FRA,Corsica,Corsica,FR-H,region,NaN,4.8,171.0,171.0,3,Europe/Paris,False,1250310924
59057,La Rochette,La Rochette,NaN,45.4586,6.1203,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,804.1,3747.0,3747.0,3,Europe/Paris,False,1250715425
59058,La Rochette,La Rochette,NaN,44.9161,4.2408,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,4.3,60.0,60.0,3,Europe/Paris,True,1250888687
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

# Both are same and this is called Boolean Mask

Bcoz we created Boolean array first and then pass it on the loc.

In [31]:
data.loc[data['lat'] > 30]

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
0,Saint-Oblas,Saint-Oblas,NaN,45.5674,5.0447,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,129.2,NaN,NaN,4,Europe/Paris,False,1250867231
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
3,Olmet,Olmet,NaN,44.9542,2.6108,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,71.0,NaN,NaN,4,Europe/Paris,True,1250526008
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59059,La Rochette,La Rochette,Rochette,45.2609,6.2881,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,55.5,NaN,NaN,4,Europe/Paris,True,1250239167
59060,La Rochette,La Rochette,NaN,45.3056,3.4747,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,14.4,NaN,NaN,4,Europe/Paris,True,1250909356
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59062,Saint-Eutrope,Saint-Eutrope,NaN,44.4535,0.5204,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,34.2,NaN,NaN,4,Europe/Paris,True,1250000461
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [32]:
# This is also called Boolean Mask

In [33]:
# When i need latitude above 45 and below 49

In [37]:
data.loc[(data['lat'] > 45) & (data['lat'] < 49)]

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
0,Saint-Oblas,Saint-Oblas,NaN,45.5674,5.0447,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,129.2,NaN,NaN,4,Europe/Paris,False,1250867231
1,Louresse,Louresse,Louresse-Rochemenier,47.2394,-0.3136,France,FR,FRA,Pays de la Loire,Pays de la Loire,FR-R,region,NaN,33.8,872.0,872.0,3,Europe/Paris,False,1250827363
2,Olmet,Olmet,NaN,45.7100,3.6614,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,10.4,161.0,161.0,3,Europe/Paris,False,1250493300
4,Gottenhouse,Gottenhouse,NaN,48.7208,7.3611,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,305.6,382.0,382.0,3,Europe/Paris,False,1250641966
6,Villelongue,Villelongue,NaN,45.8647,2.8817,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,33.0,NaN,NaN,4,Europe/Paris,False,1250958848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59057,La Rochette,La Rochette,NaN,45.4586,6.1203,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,804.1,3747.0,3747.0,3,Europe/Paris,False,1250715425
59059,La Rochette,La Rochette,Rochette,45.2609,6.2881,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,55.5,NaN,NaN,4,Europe/Paris,True,1250239167
59060,La Rochette,La Rochette,NaN,45.3056,3.4747,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,14.4,NaN,NaN,4,Europe/Paris,True,1250909356
59061,Saint-Eutrope,Saint-Eutrope,NaN,45.4181,0.1114,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,62.9,168.0,168.0,3,Europe/Paris,False,1250001345
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [38]:
data.loc[data['city'].str.contains('T')] # T starting cities are displayed

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
68,Touille,Touille,NaN,43.0803,0.9736,France,FR,FRA,Occitanie,Occitanie,FR-OCC,region,NaN,37.3,242.0,242.0,3,Europe/Paris,False,1250504101
99,Tornay,Tornay,NaN,47.7008,5.6064,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,4.2,31.0,31.0,3,Europe/Paris,False,1250411683
138,TignÃ©court,Tignecourt,NaN,48.0433,5.8931,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,5.6,106.0,106.0,3,Europe/Paris,False,1250726672
145,Toulon-sur-Allier,Toulon-sur-Allier,Toulon,46.5178,3.3592,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,29.4,1137.0,1137.0,3,Europe/Paris,False,1250102981
150,La TruchÃ¨re,La Truchere,NaN,46.5158,4.9514,France,FR,FRA,Bourgogne-Franche-ComtÃ©,Bourgogne-Franche-Comte,FR-BFC,region,NaN,43.2,220.0,220.0,3,Europe/Paris,False,1250244704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58927,Trosly-Breuil,Trosly-Breuil,Trosly,49.4003,2.9889,France,FR,FRA,Hauts-de-France,Hauts-de-France,FR-HDF,region,NaN,188.7,2072.0,2072.0,3,Europe/Paris,False,1250946348
58939,Tramecourt,Tramecourt,NaN,50.4642,2.1508,France,FR,FRA,Hauts-de-France,Hauts-de-France,FR-HDF,region,NaN,27.0,60.0,60.0,3,Europe/Paris,False,1250319380
58963,Trancis,Trancis,NaN,45.3500,2.4833,France,FR,FRA,Auvergne-RhÃ´ne-Alpes,Auvergne-Rhone-Alpes,FR-ARA,region,NaN,98.9,NaN,NaN,4,Europe/Paris,False,1250882189
58997,Wallers-TrÃ©lon,Wallers-Trelon,NaN,50.0639,4.1712,France,FR,FRA,Hauts-de-France,Hauts-de-France,FR-HDF,region,NaN,49.8,NaN,NaN,4,Europe/Paris,False,1250820767
59063,Taillis,Taillis,NaN,48.1889,-1.2389,France,FR,FRA,Bretagne,Bretagne,FR-E,region,NaN,81.2,996.0,996.0,3,Europe/Paris,False,1250655339

In [39]:
data.loc[data['city'].str.contains('I')] # I starting cities are displayed

,city,city_ascii,city_alt,lat,lng,country,iso2,iso3,admin_name,admin_name_ascii,admin_code,admin_type,capital,density,population,population_proper,ranking,timezone,same_name,id
142,Infray,Infray,Hinfray,49.9838,1.6308,France,FR,FRA,Hauts-de-France,Hauts-de-France,FR-HDF,region,NaN,50.8,NaN,NaN,4,Europe/Paris,False,1250401817
214,LâIsle-sur-Serein,L'Isle-sur-Serein,LâIsle,47.5878,4.0044,France,FR,FRA,Bourgogne-Franche-ComtÃ©,Bourgogne-Franche-Comte,FR-BFC,region,NaN,148.9,661.0,661.0,3,Europe/Paris,False,1250134477
278,Saint-Inglevert,Saint-Inglevert,Saint-Inglebert,50.8750,1.7428,France,FR,FRA,Hauts-de-France,Hauts-de-France,FR-HDF,region,NaN,119.8,791.0,791.0,3,Europe/Paris,False,1250875349
367,Ilhet,Ilhet,NaN,42.9639,0.3825,France,FR,FRA,Occitanie,Occitanie,FR-OCC,region,NaN,15.1,121.0,121.0,3,Europe/Paris,False,1250243128
621,Ispagnac,Ispagnac,NaN,44.3706,3.5358,France,FR,FRA,Occitanie,Occitanie,FR-OCC,region,NaN,16.6,893.0,893.0,3,Europe/Paris,False,1250249863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58723,Illats,Illats,NaN,44.5975,-0.3728,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,47.6,1392.0,1392.0,3,Europe/Paris,False,1250259480
58745,MÃ©ziÃ¨res-sur-Issoire,Mezieres-sur-Issoire,MÃ©ziÃ¨res,46.1075,0.9108,France,FR,FRA,Nouvelle-Aquitaine,Nouvelle-Aquitaine,FR-NAQ,region,NaN,17.1,755.0,755.0,3,Europe/Paris,False,1250252447
58839,LâIsle,L'Isle,NaN,47.9262,3.9256,France,FR,FRA,Bourgogne-Franche-ComtÃ©,Bourgogne-Franche-Comte,FR-BFC,region,NaN,22.9,NaN,NaN,4,Europe/Paris,False,1250943532
58840,LâIsle,L'Isle,NaN,46.8793,3.0822,France,FR,FRA,Bourgogne-Franche-ComtÃ©,Bourgogne-Franche-Comte,FR-BFC,region,NaN,14.2,NaN,NaN,4,Europe/Paris,True,1250041854
58892,IsÃ´mes,Isomes,NaN,47.6461,5.3042,France,FR,FRA,Grand Est,Grand Est,FR-GES,region,NaN,13.9,148.0,148.0,3,Europe/Paris,False,1250222347